# Generated by Django 4.2.27 on 2026-01-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exercisetemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='notes',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sets', to='core.exercisetemplate'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='source',
            field=models.CharField(default='manual', max_length=40),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
