# Generated by Django 4.2.27 on 2026-01-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_exerciseset_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='exerciseset',
            index=models.Index(fields=['client_uuid'], name='exercise_se_client__0ab98f_idx'),
        ),
    ]
