# Generated by Django 4.2.27 on 2025-12-24 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EGVReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('glucose_mgdl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.TextField(default='healthkit')),
                ('source_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'egv_readings',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('brand', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('serving_name', models.TextField(default='serving')),
                ('serving_grams', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('calories_kcal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'food_items',
            },
        ),
        migrations.CreateModel(
            name='MealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('eaten_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meal_events',
            },
        ),
        migrations.CreateModel(
            name='MealEventItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'meal_event_items',
            },
        ),
        migrations.CreateModel(
            name='MealTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meal_templates',
            },
        ),
        migrations.CreateModel(
            name='MealTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'meal_template_items',
            },
        ),
        migrations.CreateModel(
            name='MedicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField(unique=True)),
                ('taken_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication_events',
            },
        ),
        migrations.CreateModel(
            name='MedicationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dose_mg', models.IntegerField()),
                ('label', models.CharField(max_length=120, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medication_options',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.TextField(default='iphone')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_runs',
            },
        ),
        migrations.CreateModel(
            name='WeightReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('weight_kg', models.FloatField()),
                ('source', models.CharField(default='healthkit', max_length=40)),
                ('source_id', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weight_readings',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('activity_type', models.TextField()),
                ('duration_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('avg_hr_bpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active_energy_kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.TextField(default='healthkit')),
                ('source_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workouts',
                'indexes': [models.Index(fields=['start_at'], name='workouts_start_a_e4b6d6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source', 'source_id'), name='uniq_workout_source_sourceid'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(fields=('start_at', 'end_at', 'activity_type', 'source'), name='uniq_workout_session'),
        ),
        migrations.AddIndex(
            model_name='weightreading',
            index=models.Index(fields=['measured_at'], name='weight_read_measure_09b669_idx'),
        ),
        migrations.AddConstraint(
            model_name='weightreading',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source', 'source_id'), name='uniq_weight_source_sourceid'),
        ),
        migrations.AddConstraint(
            model_name='weightreading',
            constraint=models.UniqueConstraint(fields=('measured_at', 'source'), name='uniq_weight_measured_at_source'),
        ),
        migrations.AddField(
            model_name='medicationevent',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.medicationoption'),
        ),
        migrations.AddField(
            model_name='mealtemplateitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_items', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='mealtemplateitem',
            name='meal_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.mealtemplate'),
        ),
        migrations.AddField(
            model_name='mealeventitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_event_items', to='core.fooditem'),
        ),
        migrations.AddField(
            model_name='mealeventitem',
            name='meal_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.mealevent'),
        ),
        migrations.AddField(
            model_name='mealevent',
            name='meal_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mealtemplate'),
        ),
        migrations.AddIndex(
            model_name='egvreading',
            index=models.Index(fields=['measured_at'], name='egv_reading_measure_0b544b_idx'),
        ),
        migrations.AddConstraint(
            model_name='egvreading',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source', 'source_id'), name='uniq_egv_source_sourceid'),
        ),
        migrations.AddConstraint(
            model_name='egvreading',
            constraint=models.UniqueConstraint(fields=('measured_at', 'source'), name='uniq_egv_measured_at_source'),
        ),
        migrations.AddIndex(
            model_name='medicationevent',
            index=models.Index(fields=['taken_at'], name='medication__taken_a_4a9b33_idx'),
        ),
        migrations.AddIndex(
            model_name='mealtemplateitem',
            index=models.Index(fields=['meal_template'], name='meal_templa_meal_te_5c45c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealtemplateitem',
            constraint=models.UniqueConstraint(fields=('meal_template', 'food_item'), name='uniq_meal_template_food_item'),
        ),
        migrations.AddIndex(
            model_name='mealeventitem',
            index=models.Index(fields=['meal_event'], name='meal_event__meal_ev_df91c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealeventitem',
            constraint=models.UniqueConstraint(fields=('meal_event', 'food_item'), name='uniq_meal_event_food_item'),
        ),
        migrations.AddIndex(
            model_name='mealevent',
            index=models.Index(fields=['eaten_at'], name='meal_events_eaten_a_064b4f_idx'),
        ),
    ]
