# Generated by Django 4.2.27 on 2026-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField()),
                ('metric_type', models.TextField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('source', models.TextField(default='healthkit')),
                ('source_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_metrics',
            },
        ),
        migrations.CreateModel(
            name='SleepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('stage', models.TextField()),
                ('source', models.TextField(default='healthkit')),
                ('source_id', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sleep_sessions',
                'indexes': [models.Index(fields=['start_at'], name='sleep_sessi_start_a_967da5_idx'), models.Index(fields=['end_at'], name='sleep_sessi_end_at_abc473_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sleepsession',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source', 'source_id'), name='uniq_sleep_source_sourceid'),
        ),
        migrations.AddConstraint(
            model_name='sleepsession',
            constraint=models.UniqueConstraint(fields=('start_at', 'end_at', 'stage', 'source'), name='uniq_sleep_session'),
        ),
        migrations.AddIndex(
            model_name='healthmetric',
            index=models.Index(fields=['measured_at'], name='health_metr_measure_db5446_idx'),
        ),
        migrations.AddIndex(
            model_name='healthmetric',
            index=models.Index(fields=['metric_type'], name='health_metr_metric__aab95e_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthmetric',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source', 'source_id'), name='uniq_metric_source_sourceid'),
        ),
        migrations.AddConstraint(
            model_name='healthmetric',
            constraint=models.UniqueConstraint(fields=('measured_at', 'metric_type', 'source'), name='uniq_metric_measure_type_source'),
        ),
    ]
