# Generated by Django 4.2.27 on 2026-01-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthmetric_sleepsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('reps', models.IntegerField()),
                ('weight_kg', models.FloatField(default=0)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'exercise_sets',
                'indexes': [models.Index(fields=['performed_at'], name='exercise_se_perform_c8ed1b_idx')],
            },
        ),
    ]
